spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/moliyaviy
    username: moliyaviy
    password: moliyaviy
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
