spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/moliyaviy?stringtype=unspecified
    username: moliyaviy
    password: moliyaviy
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
